all:	alpina-BootLVM.tar.gz alpina-BootstrapRPM.tar.gz alpina-PartDisks.tar.gz

alpina-BootLVM.tar.gz:
	./buildsupport.sh build BootLVM

alpina-BootstrapRPM.tar.gz:
	./buildsupport.sh build BootstrapRPM

alpina-PartDisks.tar.gz:
	./buildsupport.sh build PartDisks

clean:
	./buildsupport.sh clean
